# Generated by Django 5.1.4 on 2025-02-21 08:31

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="instructor",
            name="salary",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                help_text="The salary of the instructor.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="user",
            field=models.OneToOneField(
                help_text="The user associated with the instructor profile.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="specialization",
            field=models.ManyToManyField(
                help_text="The subjects that the instructor specializes in.",
                related_name="instructors",
                to="instructors.subject",
            ),
        ),
    ]
