[environment]
python = "python3.12.3"

[entrypoint]
command = "uv run gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"

[phases.setup]
commands = [
    "uv sync",  # Sync dependencies and create the environment
    "uv install --upgrade pip"  # Ensure pip is upgraded
]

[phases.build]
commands = [
    "uv run python manage.py collectstatic --noinput",  # Collect static files
    "uv run python manage.py migrate"  # Apply database migrations
]

[phases.start]
command = "uv run gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
