[environment]
python = "python3.12.3"

[variables]
NIXPACKS_PYTHON_PACKAGE_MANAGER = "uv"
NIXPACKS_PYTHON_VERSION = "3.12.3"
NIXPACKS_UV_VERSION = "0.5.29"

[entrypoint]
command = "uv run gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"

[phases.setup]
commands = [
    "uv sync"
]

[phases.build]
commands = [
    "uv run manage.py collectstatic --noinput",
    "uv run manage.py migrate"
]

[phases.start]
commands = [
    "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
]
