# Generated by Django 5.1.4 on 2025-02-24 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_student_scholarship_alter_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="scholarship",
            field=models.IntegerField(
                choices=[
                    (0, "ZERO"),
                    (25, "TWENTY_FIVE"),
                    (50, "FIFTY"),
                    (75, "SEVENTY_FIVE"),
                    (100, "FULL"),
                ],
                default=0,
                help_text="The scholarship amount for the student.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
