# Generated by Django 5.1.4 on 2025-02-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("instructors", "0006_rename_specialization_instructor_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text="Course Instructor.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="instructors.instructor",
            ),
        ),
    ]
