# Generated by Django 5.1.4 on 2025-05-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enrollment_limit",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
