# Generated by Django 5.1.4 on 2025-03-21 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                help_text="Course category.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="courses.category",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("activate", "ACTIVATE"), ("inactive", "INACTIVE")],
                default="activate",
                help_text="Status of the course.",
                max_length=8,
            ),
        ),
    ]
