# Generated by Django 5.1.4 on 2025-05-20 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_enrollment_limit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                help_text="Students enrolled in the course.",
                related_name="enrolled_courses",
                through="courses.Enrollment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
