# Generated by Django 5.1.4 on 2025-03-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(help_text="Course description", max_length=300),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(help_text="Course title", max_length=255),
        ),
    ]
