# Generated by Django 5.1.4 on 2025-05-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="enrollment_limit",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
