# Generated by Django 5.1.4 on 2025-04-18 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_course_category_alter_course_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="enrollment",
            old_name="uuid",
            new_name="id",
        ),
    ]
