# Generated by Django 5.1.4 on 2025-03-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_course_description_alter_course_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(help_text="Course description"),
        ),
    ]
