# Generated by Django 5.1.4 on 2025-03-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_url",
            field=models.URLField(blank=True, help_text="Course image URL", null=True),
        ),
    ]
