# Generated by Django 5.1.4 on 2025-03-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_course_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("activate", "ACTIVATE"), ("inactive", "INACTIVE")],
                db_index=True,
                default="activate",
                help_text="Status of the course.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                db_index=True, help_text="Course title", max_length=255
            ),
        ),
    ]
