# Generated by Django 5.1.4 on 2025-03-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
