# Generated by Django 5.1.4 on 2025-03-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "MALE"), ("female", "FEMALE"), ("other", "OTHER")],
                help_text="Male or Female",
                max_length=6,
                null=True,
            ),
        ),
    ]
