# Generated by Django 5.1.4 on 2025-02-20 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="birth_date",
            new_name="date_of_birth",
        ),
    ]
