# Generated by Django 5.1.4 on 2025-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="The subjects that the instructor specializes in.",
                related_name="user",
                to="accounts.subject",
            ),
        ),
    ]
