# Generated by Django 5.1.4 on 2025-04-24 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subject",
            new_name="Specialization",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="subjects",
            new_name="specializations",
        ),
    ]
