# Generated by Django 5.1.4 on 2025-03-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "STUDENT"), ("instructor", "INSTRUCTOR")],
                editable=False,
                help_text="Instructor or Student",
                max_length=10,
                null=True,
            ),
        ),
    ]
