# Generated by Django 5.1.4 on 2025-04-23 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="scholarship",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "ZERO"),
                    (25, "TWENTY_FIVE"),
                    (50, "FIFTY"),
                    (75, "SEVENTY_FIVE"),
                    (100, "FULL"),
                ],
                db_index=True,
                default=None,
                help_text="The scholarship amount for the student.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
