# Generated by Django 5.1.4 on 2025-04-18 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="uuid",
            new_name="id",
        ),
    ]
