# Generated by Django 5.1.4 on 2025-04-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_subject_specialization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialization",
            name="description",
            field=models.TextField(
                blank=True, help_text="Specialization description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="specializations",
            field=models.ManyToManyField(
                blank=True,
                help_text="The specializations that the instructor specializes in.",
                related_name="user",
                to="accounts.specialization",
            ),
        ),
    ]
