# Generated by Django 5.1.4 on 2025-03-20 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "MALE"), ("female", "FEMALE"), ("other", "OTHER")],
                db_index=True,
                help_text="Male or Female",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=11,
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
