# Generated by Django 5.1.4 on 2025-02-21 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_student_scholarship_alter_student_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="scholarship",
            field=models.IntegerField(
                choices=[
                    (0, "0%"),
                    (25, "25%"),
                    (50, "50%"),
                    (75, "75%"),
                    (100, "100%"),
                ],
                default=0,
                help_text="The scholarship amount for the student.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                help_text="The user associated with the student profile.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
