# Generated by Django 5.1.4 on 2025-03-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(help_text="Category name", unique=True),
        ),
    ]
