# Generated by Django 5.1.4 on 2025-03-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Category name", max_length=255, unique=True
            ),
        ),
    ]
