# Generated by Django 5.1.4 on 2025-02-21 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date and time when the student enrolled in the course.",
            ),
        ),
    ]
