# Generated by Django 5.1.4 on 2025-02-25 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0002_enrollment_enrolled_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="The date and time when the student enrolled in the course.",
            ),
        ),
    ]
