# Generated by Django 5.1.4 on 2025-02-27 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0003_alter_enrollment_enrolled_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="enrolled_at",
        ),
    ]
