# Generated by Django 5.1.4 on 2025-02-19 10:11

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("instructors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.TextField(help_text="Course title")),
                ("description", models.TextField(help_text="Course description")),
                (
                    "status",
                    models.CharField(
                        choices=[("activate", "ACTIVATE"), ("inactive", "INACTIVE")],
                        default="activate",
                        help_text="Status of the course.",
                        max_length=8,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Course category.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="categories.category",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        help_text="Course Instructor.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="instructors.instructor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
