# Generated by Django 5.1.4 on 2025-04-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(help_text="Notification message"),
        ),
    ]
