# Generated by Django 5.1.4 on 2025-04-18 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instructors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructor",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="uuid",
            new_name="id",
        ),
    ]
