# Generated by Django 5.1.4 on 2025-02-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "instructors",
            "0002_subject_instructor_salary_alter_instructor_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="degree",
            field=models.CharField(
                choices=[("master", "MASTER"), ("doctorate", "DOCTORATE")],
                help_text="The degree of the instructor.",
                max_length=9,
                null=True,
            ),
        ),
    ]
