# Generated by Django 5.1.4 on 2025-02-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructors", "0003_instructor_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="salary",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                help_text="The salary of the instructor.",
                max_digits=12,
            ),
        ),
    ]
