# Generated by Django 5.1.4 on 2025-02-24 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instructors", "0005_alter_instructor_degree"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructor",
            old_name="specialization",
            new_name="subjects",
        ),
    ]
