# Generated by Django 5.1.4 on 2025-03-02 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instructors", "0006_rename_specialization_instructor_subjects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructor",
            name="salary",
        ),
    ]
