# Generated by Django 5.1.4 on 2025-03-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructors", "0007_remove_instructor_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.TextField(
                blank=True, help_text="Subject description", null=True
            ),
        ),
    ]
