# Generated by Django 5.1.4 on 2025-03-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructors", "0008_subject_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="degree",
            field=models.CharField(
                choices=[
                    ("no", "NO"),
                    ("bachelor", "BACHELOR"),
                    ("master", "MASTER"),
                    ("doctorate", "DOCTORATE"),
                ],
                db_index=True,
                default="no",
                help_text="The degree of the instructor.",
                max_length=9,
            ),
        ),
    ]
